"""Regenerate shared/hash_test_vectors.json from the Python reference implementation.

    cd server && uv run python scripts/generate_hash_vectors.py

The vectors pin down assignment for the TypeScript SDK: sdk-js must reproduce every one.
Regenerate only when assignment deliberately changes, and then both test suites must pass.
"""

import json
from pathlib import Path

from abtest.assignment import WeightedVariant, assign, bucket, flag_enabled, hash32

HASH_INPUTS = [
    # The empty string, and every tail length from 1 to 8 bytes (MurmurHash3 reads 4-byte
    # blocks, then a 1-3 byte tail: ports usually get the tail wrong).
    "", "a", "ab", "abc", "abcd", "abcde", "abcdef", "abcdefg", "abcdefgh",
    # ASCII ids and text
    "user-1", "user_12345", "User-1", "Hello, world!", "a b", "tab\tseparated",
    "The quick brown fox jumps over the lazy dog", "~!@#$%^&*()_+-=[]{}|;',./<>?",
    # Numeric-looking ids (hashed as text, never as numbers)
    "0", "1", "42", "007", "-1", "3.14", "1e10", "123456789", "18446744073709551616",
    "00000000-0000-0000-0000-000000000000",
    # Multi-byte UTF-8, including characters that straddle a 4-byte block
    "aé", "aaé", "aaaé", "café", "naïve", "Ünïcödé", "日本語", "中文用户", "한국어",
    "Ελληνικά", "русский", "עברית", "العربية", "हिन्दी",
    # The same visible text in two Unicode forms: ids are hashed as-is, never normalized
    "é", "é",
    # Emoji: 4-byte characters, skin-tone modifiers, ZWJ sequences, flags
    "😀", "👍🏽", "👨‍👩‍👧‍👦", "🇺🇸", "user-🚀-7", "😀a",
    # Invisible characters
    "﻿bom", "zero​width",
    # The exact strings assignment hashes
    "checkout-button:traffic:user-1", "checkout-button:variant:user-1", "dark-mode:rollout:user-42",
    # Long strings
    "x" * 1000, "user-" + "9" * 256, "日本語🚀" * 300,
]  # fmt: skip

FIFTY_FIFTY = [WeightedVariant("control", 5000, 0), WeightedVariant("treatment", 5000, 1)]
THREE_WAY = [
    WeightedVariant("a", 3300, 0),
    WeightedVariant("b", 3300, 1),
    WeightedVariant("c", 3400, 2),
]
# Listed out of position order: assignment must sort by position, not by list order.
UNSORTED = [WeightedVariant("second", 1000, 1), WeightedVariant("first", 9000, 0)]

EXPERIMENTS = [
    ("checkout-button", 10_000, FIFTY_FIFTY),
    ("checkout-button", 5_000, FIFTY_FIFTY),
    ("pricing-page", 10_000, THREE_WAY),
    ("onboarding", 2_500, UNSORTED),
    ("paused-rollout", 0, FIFTY_FIFTY),
]
# user-3 and user-31 are included so that every variant of every experiment appears.
USERS = [
    "user-1", "user-2", "user-3", "user-31", "user-42",
    "alice@example.com", "12345", "日本語", "😀",
]  # fmt: skip
FLAGS = [("dark-mode", True, 5_000), ("dark-mode", False, 10_000), ("new-nav", True, 10_000)]


def main() -> None:
    vectors = {
        "about": (
            "MurmurHash3 x86_32, seed 0, over UTF-8 bytes, unsigned; bucket = hash mod 10000. "
            "Generated by server/scripts/generate_hash_vectors.py "
            "from server/src/abtest/assignment.py."
        ),
        "hashes": [{"input": s, "hash": hash32(s), "bucket": bucket(s)} for s in HASH_INPUTS],
        "assignments": [
            {
                "experiment": key,
                "user": user,
                "traffic_bp": traffic,
                "variants": [
                    {"key": v.key, "weight_bp": v.weight_bp, "position": v.position}
                    for v in variants
                ],
                "variant": assign(key, user, traffic, variants),
            }
            for key, traffic, variants in EXPERIMENTS
            for user in USERS
        ],
        "flags": [
            {
                "flag": key,
                "user": user,
                "enabled": enabled,
                "rollout_bp": rollout,
                "on": flag_enabled(key, user, enabled, rollout),
            }
            for key, enabled, rollout in FLAGS
            for user in USERS
        ],
    }
    path = Path(__file__).resolve().parents[2] / "shared" / "hash_test_vectors.json"
    path.write_text(json.dumps(vectors, ensure_ascii=False, indent=1) + "\n")
    print(f"wrote {len(vectors['hashes'])} hash, {len(vectors['assignments'])} assignment, "
          f"and {len(vectors['flags'])} flag vectors to {path}")  # fmt: skip


if __name__ == "__main__":
    main()
